name: copy parent properties

on:
  issues:
    types: [opened]

jobs:
  copy-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Get parent issue number from body
        id: get_parent
        run: |
          parent=$(echo "${{ github.event.issue.body }}" | grep -oE '#[0-9]+' | head -1 | tr -d '#')
          echo "parent_number=$parent" >> $GITHUB_OUTPUT

      - name: Get parent issue info
        if: steps.get_parent.outputs.parent_number != ''
        uses: actions/github-script@v7
        id: parent_info
        with:
          script: |
            const parent = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.get_parent.outputs.parent_number }}
            });
            return {
              labels: parent.data.labels.map(l => l.name),
              milestone: parent.data.milestone ? parent.data.milestone.number : null
            };

      - name: Copy labels and milestone to sub-issue
        if: steps.parent_info.outputs.labels != ''
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ${{ steps.parent_info.outputs.labels }},
              milestone: ${{ steps.parent_info.outputs.milestone }}
            });
